// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	DeleteEvent(ctx context.Context, eventID int64) error
	GetEvent(ctx context.Context, eventID int64) (Event, error)
	GetEvents(ctx context.Context, ids []int64) ([]Event, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
}

var _ Querier = (*Queries)(nil)
